### ISSUE TITLE
FM Radio?

### ISSUE THREAD

**Issue by marclava** [ItsVixano-releases/LineageOS_daisy#1]
The Mi A2 lite have a (real) FM radio, but it's not activated in the ROM.
Is there a way to fix this issue?

**Comment by ItsVixano** [comment]
I could switch to QCOM fm implementation for the next update since AOSP one doesn't get compiled in the current state (and even if it gets, RDS wouldn't work anyway)

**Comment by ItsVixano** [comment]
> That's reassuring; I chose the phone in part because of its FM radio. Will I be able to update without reinstalling?

Sure, via OTA or by flashing manually the package

**Comment by ItsVixano** [comment]
> Will it come with a basic app? All I found that could maybe work is: https://github.com/vladislav805/RFM-Radio But it does not work, probably because some kernel drivers are not compiled?

- Yeah
- Will be fixed automatically once i switch to QCOM fm impl

**Comment by ItsVixano** [comment]
Added it on the latest OTA :D

**Comment by marclava** [comment]
It works perfectly, thanks!
