### ISSUE TITLE
BUG in recent apps

### ISSUE THREAD

**Issue by mustarde** [ItsVixano-releases/LineageOS_daisy#10]
Actions window doesn't show up for the current open app on the recents page (when clicking on the app icon.)

Clicking on the icon of the current open app does nothing: 
![Screenshot_20230710-134258_Chrome](https://github.com/ItsVixano-releases/LineageOS_daisy/assets/64613049/ceed8593-4e33-44bc-89d5-80d4d6596f3a)

Clicking on the icon of the other app shows the mini menu as expected: 
![Screenshot_20230710-134312_Chrome](https://github.com/ItsVixano-releases/LineageOS_daisy/assets/64613049/88f98db1-7df0-4b4c-aaf3-8b8e17e588f0)

**Comment by ItsVixano** [comment]
the new build with july patches should fix that issue
