### ISSUE TITLE
Can you add support for KernelSU?

### ISSUE THREAD

**Issue by Heus-Sueh** [ItsVixano-releases/LineageOS_daisy#11]
https://github.com/tiann/KernelSU

**Comment by Heus-Sueh** [comment]
> No, No, and No
> 
> Not only that's [not allowed by LineageOS team](https://github.com/LineageOS/charter/blob/master/device-support-requirements.md#root-su), KernelSU is not supposed to be shipped on production becuase, you know, it equals to shipping the rom pre-rooted, and that can introduce a lot of unwanted vulnerability (fun fact, the official AOSPA build for surya was [taked down](https://github.com/AOSPA/ota/commit/4e2d79cb6ebcd573390df2a57af4044ec8e0675b) for this exact reason). Other than that, KernelSU can introduce a series of regressions due on how they implemented it.
> 
> If you badly want KernelSU, [build the kernel](https://github.com/xiaomi-msm8953-devs/android_kernel_xiaomi_msm8953) for your self with KernelSU enabled

I didn't know about this controversy, is kernelSU so intrusive that it's worse than magisk or are both bad?

**Comment by chiteroman** [comment]
> If you badly want KernelSU, [build the kernel](https://github.com/xiaomi-msm8953-devs/android_kernel_xiaomi_msm8953) for your self with KernelSU enabled

How can I build only the kernel ?
