### ISSUE TITLE
[Enhancement] patch for daisy to make status bar icons closer to each other

### ISSUE THREAD

**Issue by bomzhellino** [ItsVixano-releases/LineageOS_daisy#14]
Since you are applying some of your own patches, i would like to suggest one useful patch.
Since the device has a very large notch, there is little space left in the status bar for notification icons. This patch brings icons closer to each other:
https://github.com/eremitein/treble-patches/blob/caos/patches/personal/frameworks_base/0079-tuning-statusbar-looking.patch
Maybe you can adapt it for los 20.

**Comment by ItsVixano** [comment]
The padding is already inline with whatever stock does
