### ISSUE TITLE
[Enhancement] Mulch System Webview support

### ISSUE THREAD

**Issue by bomzhellino** [ItsVixano-releases/LineageOS_daisy#15]
I see that the ROM includes Bromite Webview support.
Since this project has recently been abandoned, it may be useful to include support for Mulch Webview by DivestOS.
Here is the overlay for it:
https://github.com/A4Alpha/mulch-webview-overlay

**Comment by ItsVixano** [comment]
Uhm, maybe, will see

**Comment by ItsVixano** [comment]
![Screenshot_20230911-225036_Settings](https://github.com/ItsVixano-releases/LineageOS_daisy/assets/50358281/3c7fe228-7c70-439d-bf1c-4127fc4b8dd9)

:D
