### ISSUE TITLE
[Enhancement] Please add Adreno Idler to the kernel

### ISSUE THREAD

**Issue by bomzhellino** [ItsVixano-releases/LineageOS_daisy#16]
Hi, Giovanni.
Thanks for the September los20 build and Mulch Webview support. Good job.
If you have time, please consider adding Adreno Idler to the kernel for better battery backup.
Here are the test results from the xda forum:

1. Adreno idler off - 46.3% battery drain, can expect approx. 6hrs 5mins of video playback on 100% battery charge.
2. Adreno idler on - 25.5% battery drain, can expect approx. 11hrs 2mins of video playback on 100% battery charge.

Best regards.

**Comment by ItsVixano** [comment]
The tests has been made nearly 8 years ago on a totally different device, and, things really changed nowadays.

Adreno Idler is not a thing anymore (even the creator himself doesn't even like it ¯\_ (ツ) _/¯ ) and even if i introduce this "now dirty" rice, you won't really gain that much.

Feel free to do your own tests, and see if that's really the issue.

**Comment by bomzhellino** [comment]
OK. You are a professional, I trust you. I just thought that lowering the gpu frequency to 19 MHz when idle made sense.
