### ISSUE TITLE
Bootloop after latest update (12/10/2023)

### ISSUE THREAD

**Issue by MaxWasTakenYT** [ItsVixano-releases/LineageOS_daisy#17]
After clicking reboot on the update notification it just rebooted and then weirdly enough it started bootlooping
Still haven't solved :(

(also happens when i tried to flash magisk)

**Comment by ItsVixano** [comment]
> After clicking reboot on the update notification it just rebooted and then weirdly enough it started bootlooping Still haven't solved :(
> 
> (also happens when i tried to flash magisk)

Hey, are you able to send a log regard the issue ??
Also retry to reflash LineageOS with just a simple `adb sideload` + gapps if you done it previously

**Comment by MaxWasTakenYT** [comment]
Thanks for help but there's another problem now..
It worked just fine and booted like always but now mindthegapps are dead.. (google play services doesn't work anymore)
i also already tried to refresh the latest mindthegapps version so would you be able to identify the problem?

**Comment by ItsVixano** [comment]
Ig the best solution is to reflash los again by formatting data

or you could attempt doing something 

reboot to recovery, enable adb and mount /system (on advanced settings), and remove `/system/addon.d/30-gapps.sh` with adb shell

then reflash LineageOS recovery and don't flash anything else

reboot again on recovery, flash mindthegapps, reboot and give manual internet permissions on gapps packages

**Comment by MaxWasTakenYT** [comment]
Im trying now thanks for help, im gonna let you know if this works.

**Comment by MaxWasTakenYT** [comment]
Hey i just rebooted and i have to give the permissions, do you mean like only the google play services? (when i booted it still gave me the google play services crash popup)

**Comment by ItsVixano** [comment]
yeah on Settings -> Search for Google apps -> Mobile Data and Wi-Fi -> Allow Network access

**Comment by MaxWasTakenYT** [comment]
they are already activated but apps like google play store or youtube still do not work, any other way of solving this?

**Comment by MaxWasTakenYT** [comment]
i cannot format now becuase the last backup i did was like last year or something

**Comment by MaxWasTakenYT** [comment]
ok so i need to give you the other reason which makes unable to format: my screen is cracked A LOT and the touchscreen is like almost destroyed so i literally cannot click the two vertical sides of the screen.. and for that reason i use an app that spawns

**Comment by MaxWasTakenYT** [comment]
mislicked the close button💀
and so the only way is to format right?
but at least is there a way to like backup before formatting?

**Comment by ItsVixano** [comment]
> mislicked the close button💀 and so the only way is to format right? but at least is there a way to like backup before formatting?

maybe, is the only fast way to resolve that issue
for whatsapp you could generate a local backup and use `adb pull /sdcard/Android/media/com.whatsapp`

> if you want we can speak italian since im italian too

i prefer in English here since maybe someone could come across this issue :D

**Comment by MaxWasTakenYT** [comment]
> since maybe someone could come across this issue :D
oh yeah you're right

> for whatsapp you could generate a local backup
how do i generate the local backup?

**Comment by ItsVixano** [comment]
> how do i generate the local backup?

on settings -> chat, something like that, you can generate a backup without the use of gdrive

**Comment by MaxWasTakenYT** [comment]
> on settings -> chat, something like that, you can generate a backup without the use of gdrive

oh thanks it worked, just one other question: is nextcloud ANY good to backup files?

**Comment by ItsVixano** [comment]
> oh thanks it worked, just one other question: is nextcloud ANY good to backup files?

i mean, i would still prefer some self-hosted service :D, this is more like a personal preference tho

**Comment by MaxWasTakenYT** [comment]
ok thanks im probably gonna format now (or tomorrow i guess)
