### ISSUE TITLE
Notification LED settings being ignored

### ISSUE THREAD

**Issue by Ch1llb0** [ItsVixano-releases/LineageOS_daisy#2]
Currently, the notification LED settings are being ignored: the LED does only turn on, it doesn't flash at all.

Can this behaviour be changed and the settings (also in-app) be reflected by the LED again? It used to work with LOS 18.1.

**Comment by ItsVixano** [comment]
Hi, i've currently reworking the device trees as for now, i'll address notification leds related issues once i finish everything 👌

**Comment by Ch1llb0** [comment]
Thanks for the reply and the info! Great to hear it's on the list - can't wait for a fix here 😊

**Comment by Ch1llb0** [comment]
Any news on this? 😊

**Comment by ItsVixano** [comment]
haven't yet implemented this logic properly, i'm busy with school exams right now :D

**Comment by ItsVixano** [comment]
https://github.com/ItsVixano-releases/LineageOS_daisy/assets/50358281/fd3cc048-e6da-4dc8-a0fc-6c82345c9b1c

Just doing a couple of stuffs during breaks :D

**Comment by Ch1llb0** [comment]
Great stuff! If that would also affect how the notification light reacts to Signal notifications, it would be another plus... 😊👍🏻

**Comment by ItsVixano** [comment]
Hey, is everything fine on today update (regard the notification led) ??

**Comment by Ch1llb0** [comment]
I'll check it out, thanks for letting me know 👍🏻

**Comment by Ch1llb0** [comment]
I've installed the update, but either GApps is crashing (older version installed, MindTheGapps-13.0.0-arm64-20221025_100653) or the phone is really laggy, apps are crashing constantly and GApps can't get any internet connection (newest GApps version installed, MindTheGapps-13.0.0-arm64-20230408_162909). Any ideas?

I've installed on different slot, wiping Davik before installed, after flashing Lineage, before installing GApps on new slot and before booting into system.

**Comment by ItsVixano** [comment]
> I've installed the update, but either GApps is crashing (older version installed, MindTheGapps-13.0.0-arm64-20221025_100653) or the phone is really laggy, apps are crashing constantly and GApps can't get any internet connection (newest GApps version installed, MindTheGapps-13.0.0-arm64-20230408_162909). Any ideas?
> 
> I've installed on different slot, wiping Davik before installed, after flashing Lineage, before installing GApps on new slot and before booting into system. Side note: Installing the version before this on another Mi A2 Lite with the older GApps version worked fine a week ago.
> 
> I'll stay on the old, stable slot without this update for now.

You were supposed to flash gapps before rebooting to system

anyway you need to allow internet access to gms application since the firewall disables it automatically

you can still use the old gapps package hosted here (http://downloads.codefi.re/jdcteam/javelinanddart/gapps/old/MindTheGapps-13.0.0-arm64-20221025_100653.zip) btw

**Comment by Ch1llb0** [comment]
> You were supposed to flash gapps before rebooting to system

I did. I installed Lineage, rebooted to other slot (recovery) and then installed GApps.

I've consequently tried reflashing Lineage and flashing FlameGApps, but this ends me up in aboot loop. FlameGApps is really persistent as it recovers itself after flashing ROMs every time. Any idea what I can could do? I'd like to prevent a full reset...

**Comment by ItsVixano** [comment]
You should be able to cleanup MindTheGapos if you delete /system/addon.d/30 gapps.sh file (you can mount system partition on los recovery, give it read-write permissions with `mount -o remount,rw /mnt/system`, and be able to delete that file `rm -rf /mnt/system/addon.d/30 gapps.sh`)

not sure about FlameGapps, ig it uses the same addon way

**Comment by ItsVixano** [comment]
Have you connected the devices and enabled adb on advanced settings ?

**Comment by Ch1llb0** [comment]
adb should've been enabled on my phone all this time, yes. Trying to figure out the driver situation right now.

**Comment by ItsVixano** [comment]
> adb should've been enabled on my phone all this time, yes. Trying to figure out the driver situation right now.

https://developer.android.com/studio/run/win-usb  here :D

**Comment by Ch1llb0** [comment]
Yeah, have it installed, but can't select the driver when the `Android` device shows up in device manager... Hell, I've done this numerous times and now nothing seems to work.

**Comment by ItsVixano** [comment]
> Yeah, have it installed, but can't select the driver when the `Android` device shows up in device manager... Hell, I've done this numerous times and now nothing seems to work.

didn't adb sideload worked before ?

**Comment by Ch1llb0** [comment]
I've installed via TWRP all this time... Has worked for a few Mi A2 Lite, LOS and more than one LOS version. So, no adb sideloading just now, no.

**Comment by ItsVixano** [comment]
> I've installed via TWRP all this time... Has worked for a few Mi A2 Lite, LOS and more than one LOS version. So, no adb sideloading just now, no.

ah with twrp? you can do it directly on the file manager then (after you mount /system ofc)

**Comment by Ch1llb0** [comment]
Ok, have mounted system in both slots via TWRP now and deleted `gapps` as well as `flame` (a second file located in `/system/addon.d/` on both slots). Will see what this does now...

**Comment by ItsVixano** [comment]
> Ok, have mounted system in both slots via TWRP now and deleted `gapps` as well as `flame` (a second file located in `/system/addon.d/` on both slots). Will see what this does now...

well you are supposed to reflash the rom afterwards

**Comment by Ch1llb0** [comment]
Yup, that's what I did... Reflashed latest Lineage, changed slot and installed MindTheGApps. Did manage to boot into system now!

> anyway you need to allow internet access to gms application since the firewall disables it automatically

Coming back to this... The app has permission to access the internet in app settings. Any other location I have to look?

Google Wallett crashes all the time.

**Comment by ItsVixano** [comment]
> Yup, that's what I did... Reflashed latest Lineage, changed slot and installed MindTheGApps. Did manage to boot into system now!
> 
> > anyway you need to allow internet access to gms application since the firewall disables it automatically
> 
> Coming back to this... The app has permission to access the internet in app settings. Any other location I have to look?
> 
> Google Wallett crashes all the time.

Check for google play services internet permissions too

**Comment by Ch1llb0** [comment]
Ok, I had to install the older GApps version and then allow internet access for Google Play. That part works now. 👍🏻 🥳 

But Google Wallett is still crashing when launching the app...

**Comment by ItsVixano** [comment]
Not sure about that tbh, i don't even use gapps on my devices

**Comment by Ch1llb0** [comment]
Hm, that's a bummer. I can survive without the Wallet, but it used to work fine before...

The whole phone has become really slow and unresponsive with the update though 😞

**Comment by ItsVixano** [comment]
uhm, it works fine here, as it always did, not sure if gapps done something 
i recommend clearing the cache on recovery, worst case scenario make a backup of everything and format it

**Comment by Ch1llb0** [comment]
I've always cleared Dalvik between each an every step, last time after installing GApps and booting into system... Will try one LOS version older to compare.

**Comment by Ch1llb0** [comment]
Ok, downgrading doesn't seem to work... LOS then doesn't even try to boot up.

**Comment by ItsVixano** [comment]
> Ok, downgrading doesn't seem to work... LOS then doesn't even try to boot up.

well that expected to happened on FBE
reflashing the current build should be fine 

anyway as i said, you better backup data and reformat everything

**Comment by Ch1llb0** [comment]
It seems like Google Play needed some time to sort things out, that's why the phone was feeling really sluggish. It's fine now and the playstore seems to work fine. The Wallet doesn't, but that's OK, I suppose.

Before anything else, thank you very much for your patient help! I was already considering my data lost (yes, I was too confident and forgot to backup). So, thank you! 🙏🏻

Will test the rest now, including Signal notifications 👍🏻

One things I've found already: When the charging notification LED is active, other notifications don't override this. It would be really useful to have all other notifications that make the LED pulse a higher priority than the charging notification. Otherwise messages e.g. can't be noticed from the looks of the LED while the phone is charging. Would it be possible to adjust this?
Same as the charging LED not showing until 100% atm, but turning off at 90%. It would be cool to have the notification until the phone actually stops charging. 😊

**Comment by Ch1llb0** [comment]
The notifications LED seems to be working near perfect now - even with Signal. Great work, thank you! 🙏🏻

The only thing left would be the charging LED issue described before - if that's something that can even be adjusted.

**Comment by Ch1llb0** [comment]
I've just installed the latest August update: First thing I noticed is Google backup as well as the Wallet app are working again now and the phone is a lot quicker again...

But the charging LED priority hasn't changed: If you enable the charging LED, other notifications are not shown by a blinking LED. Can this still be adjusted or is it our of your hands, @ItsVixano?

Great work though - it's a really nice ROM! 🥳

**Comment by ItsVixano** [comment]
> I've just installed the latest August update: First thing I noticed is Google backup as well as the Wallet app are working again now and the phone is a lot quicker again...
> 
> But the charging LED priority hasn't changed: If you enable the charging LED, other notifications are not shown by a blinking LED. Can this still be adjusted or is it our of your hands, @ItsVixano?
> 
> Great work though - it's a really nice ROM! 🥳

Not in my priority for now, anyway thanks for the report :D
