### ISSUE TITLE
Upgrade from 19 to 20?

### ISSUE THREAD

**Issue by marclava** [ItsVixano-releases/LineageOS_daisy#5]
It is possible to upgrade from 19 to 20 using OTA?
Also, is FM radio still enabled in 20?

**Comment by ItsVixano** [comment]
yep, make sure to reflash gapps and/or magisk if you have flashed them before

**Comment by marclava** [comment]
The update manager don't show version 20, even after I hit the refresh button. Can I upgrade the system using a USB cable?
